export const comidas = [
  {id: 1, name: "hamburguesa de carne"},
  {id: 2, name: "hamburguesa veggie"},
  {id: 3, name: "hamburguesa de pollo"},
  {id: 4, name: "milanesa de carne"},
  {id: 5, name: "milanesa veggie"},
  {id: 6, name: "milanesa de pollo"},
  {id: 7, name: "sandwich de bondiola"},
  {id: 8, name: "sandwich de pollo"},
  {id: 9, name: "pizza a la piedra"},
  {id: 10, name: "pizza al molde"},
  {id: 11, name: "pizza veggie"},
  {id: 12, name: "empanada de carne"},
  {id: 13, name: "empanada de pollo"},
  {id: 14, name: "empanada de jamón y queso"},
  {id: 15, name: "ensalada"},
  {id: 16, name: "sopa crema"},
]

export const bebidas = [
  {id: 17, name: "gaseosa sabor cola"},
  {id: 18, name: "gaseosa sabor limón"},
  {id: 19, name: "gaseosa sabor naranja"},
  {id: 20, name: "agua saborizada"},
  {id: 21, name: "cerveza rubia"},
  {id: 22, name: "cerveza negra"},
  {id: 23, name: "cerveza IPA"},
  {id: 24, name: "vino blanco"},
  {id: 25, name: "vino tinto"},
  {id: 26, name: "vino rosado"},
  {id: 27, name: "agua mineral con gas"},
  {id: 28, name: "agua mineral sin gas"},
  {id: 29, name: "agua tónica"},
]

export const postres = [
  {id: 30, name: "helado tipo bombón escocés"},
  {id: 31, name: "helado tipo cassata"},
  {id: 32, name: "tiramisu"},
  {id: 33, name: "ensalada de frutas"},
  {id: 34, name: "flan de vainilla"},
  {id: 35, name: "budín de pan"},
]

export const ingredientes = [
  {id: 1, name: "tomate"},
  {id: 2, name: "lechuga"},
  {id: 3, name: "queso Cheddar"},
  {id: 4, name: "cebolla"},
  {id: 5, name: "panceta"},
  {id: 6, name: "huevo frito"},
  {id: 7, name: "palta"},
  {id: 8, name: "champiñones"}, 
  {id: 9, name: "morrones"},
  {id: 10, name: "jamón"},
  {id: 11, name: "queso Mozzarella"},  
  {id: 12, name: "pepperoni"},
  {id: 13, name: "pollo"},
  {id: 14, name: "queso provolone"},
  {id: 15, name: "salchicha italiana"},
  {id: 16, name: "aceitunas verdes"},
  {id: 17, name: "aceitunas negras"},
  {id: 18, name: "maiz dulce"},
  {id: 19, name: "esparragos"},
  {id: 20, name: "orégano"},
  {id: 21, name: "albahaca fresca"},
  {id: 22, name: "tomillo"},
  {id: 23, name: "romero"},
  {id: 24, name: "anchoas"},
  {id: 25, name: "ajo"},
  {id: 26, name: "huevo duro"},
  {id: 27, name: "ananá"},
  {id: 28, name: "mostaza"},
  {id: 29, name: "mayonesa"},
  {id: 30, name: "barbacoa"},
  {id: 31, name: "ketchup"},
  {id: 32, name: "salsa golf"},
  {id: 33, name: "salsa cesar"},
  {id: 34, name: "chimichurri"},
  {id: 35, name: "salsa criolla"},
  {id: 36, name: "pasas de uva"},
  {id: 37, name: "crutones de pan"},
  {id: 38, name: "queso azul"},
  {id: 39, name: "salsa de tomate"},
  {id: 40, name: "salsa portuguesa"},
  {id: 41, name: "salsa napolitana"},
  {id: 42, name: "salsa picante"},
  {id: 43, name: "salsa rosa"},
  {id: 44, name: "dulce de leche"},
  {id: 45, name: "crema de leche"},
]
