export const comidas = [
  {id: 1,"hamburguesa de carne"},
  {id: 2,"hamburguesa veggie"},
  {id: 3,"hamburguesa de pollo"},
  {id: 4,"milanesa de carne"},
  {id: 5,"milanesa veggie"},
  {id: 6,"milanesa de pollo"},
  {id: 7,"sandwich de bondiola"},
  {id: 8,"sandwich de pollo"},
  {id: 9,"pizza a la piedra"},
  {id: 10,"pizza al molde"},
  {id: 11,"pizza veggie"},
  {id: 12,"empanada de carne"},
  {id: 13,"empanada de pollo"},
  {id: 14,"empanada de jamón y queso"},
  {id: 15,"ensalada"},
  {id: 16,"sopa crema"},
]

export const bebidas = [
  {id: 17,"gaseosa sabor cola"},
  {id: 18,"gaseosa sabor limón"},
  {id: 19,"gaseosa sabor naranja"},
  {id: 20,"agua saborizada"},
  {id: 21,"cerveza rubia"},
  {id: 22,"cerveza negra"},
  {id: 23,"cerveza IPA"},
  {id: 24,"vino blanco"},
  {id: 25,"vino tinto"},
  {id: 26,"vino rosado"},
  {id: 27,"agua mineral con gas"},
  {id: 28,"agua mineral sin gas"},
  {id: 29,"agua tónica"},
]

export const postres = [
  {id: 30,"helado tipo bombón escocés"},
  {id: 31,"helado tipo cassata"},
  {id: 32,"tiramisu"},
  {id: 33,"ensalada de frutas"},
  {id: 34,"flan de vainilla"},
  {id: 35,"budín de pan"},
]

export const ingrdientes = [
  {id: 1, "tomate"},
  {id: 2, "lechuga"},
  {id: 3, "queso Cheddar"},
  {id: 4, "cebolla"},
  {id: 5, "panceta"},
  {id: 6, "huevo frito"},
  {id: 7, "palta"},
  {id: 8, "champiñones"}, 
  {id: 9, "morrones"},
  {id: 10,"jamón"},
  {id: 11,"queso Mozzarella"},  
  {id: 12,"pepperoni"},
  {id: 13,"pollo"},
  {id: 14,"queso provolone"},
  {id: 15,"salchicha italiana"},
  {id: 16,"aceitunas verdes"},
  {id: 17,"aceitunas negras"},
  {id: 18,"maiz dulce"},
  {id: 19,"esparragos"},
  {id: 20,"orégano"},
  {id: 21,"albahaca fresca"},
  {id: 22,"tomillo"},
  {id: 23,"romero"},
  {id: 24,"anchoas"},
  {id: 25,"ajo"},
  {id: 26,"huevo duro"},
  {id: 27,"ananá"},
  {id: 28,"mostaza"},
  {id: 29,"mayonesa"},
  {id: 30,"barbacoa"},
  {id: 31,"ketchup"},
  {id: 32,"salsa golf"},
  {id: 33,"salsa cesar"},
  {id: 34,"chimichurri"},
  {id: 35,"salsa criolla"},
  {id: 36,"pasas de uva"},
  {id: 37,"crutones de pan"},
  {id: 38,"queso azul"},
  {id: 39,"salsa de tomate"},
  {id: 40,"salsa portuguesa"},
  {id: 41,"salsa napolitana"},
  {id: 42,"salsa picante"},
  {id: 43,"salsa rosa"},
  {id: 44,"dulce de leche"},
  {id: 45,"crema de leche"},
]
